#pragma once

// Auto-generated master include for Cat Run sprites

#include "CAT_WHITE_WALK0.h"
#include "CAT_WHITE_WALK1.h"
#include "CAT_WHITE_JUMP.h"
#include "CAT_WHITE_DUCK.h"
#include "CAT_BLACK_WALK0.h"
#include "CAT_BLACK_WALK1.h"
#include "CAT_BLACK_JUMP.h"
#include "CAT_BLACK_DUCK.h"
#include "CAT_CALICO_WALK0.h"
#include "CAT_CALICO_WALK1.h"
#include "CAT_CALICO_JUMP.h"
#include "CAT_CALICO_DUCK.h"
#include "DOG_0.h"
#include "DOG_1.h"
#include "DOG_RUN_0.h"
#include "DOG_RUN_1.h"
#include "BULLY_0.h"
#include "BULLY_1.h"
#include "COOL_0.h"
#include "COOL_1.h"
#include "PUPPY_0.h"
#include "PUPPY_1.h"
#include "FOOD.h"
#include "FISH.h"
#include "GROUND.h"
#include "GRASS_TILE.h"
#include "WATER.h"
#include "HOLE.h"
#include "TREE.h"
#include "BUSH.h"
#include "CRATE.h"
#include "FENCE.h"
#include "QBLOCK.h"
#include "BRICK.h"
#include "PLATFORM.h"
#include "CLOUD.h"
#include "FLAG.h"
#include "HOUSE.h"
#include "MOUNTAIN.h"
#include "BG_TREE_A.h"
#include "BG_TREE_B.h"

